name: Deploy application

on:
  push:
    branches:
      - "**"
  workflow_call:

jobs:
  deploy:
    environment: production
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      
      - name: Set up Docker tags
        id: tags
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
          
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "tags=latest,${SHA_SHORT},${BRANCH_NAME}" >> $GITHUB_OUTPUT
          else
            echo "tags=${BRANCH_NAME},${SHA_SHORT}" >> $GITHUB_OUTPUT
          fi
      
      - name: Publish Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: piarre/alert-manager-free-mobile
          registry: ghcr.io
          username: piarre
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: "${{ steps.tags.outputs.tags }}"

  notify:
    needs: deploy
    uses: ./.github/workflows/notify.yml
    with:
      message: "✅ Deployment of `${{ github.repository }}` on branch `${{ github.ref_name }}` successful! 🚀"
    secrets: inherit