name: Notify

on:
  workflow_call:
    inputs:
      message:
        description: 'Message to send'
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        run: |
          curl "https://smsapi.free-mobile.fr/sendmsg?user=${{ secrets.FREE_MOBILE_USER }}&pass=${{ secrets.FREE_MOBILE_PASS }}&msg=${{ inputs.message }}"